[tox]
envlist = flake8, black, isort

[testenv:black]
deps = black
commands = black {posargs}

[testenv:flake8]
deps = flake8
commands = flake8 {posargs}

[testenv:isort]
deps = isort
commands = isort {posargs}

[black]
line-length = 160
fast = true
skip-string-normalization = true
force-exclude = 
    (
       .*/migrations/
     | .*/__pycache__/
     | .tox/
     | .pytest_cache/
     | build/
     | dist/
     | *.egg-info/
    )

[isort]
profile = black
line_length = 160
known_first_party = ansible_collections.hashicorp.terraform
lines_after_imports = 2
lines_between_types = 1
extend_skip = 
    .tox
    .pytest_cache
    __pycache__
    build
    dist
    *.egg-info

[flake8]
max-line-length = 160
extend-ignore = E203, E402, F841, DOC
exclude = 
    .tox,
    .pytest_cache,
    __pycache__,
    *.egg-info,
    build,
    dist,
    .git,
    .github,
    .mypy_cache,
    .venv,
    venv,
    __init__.py
per-file-ignores = 
    plugins/modules/*:E402
    tests/**.py:S101
count = true
statistics = true 