---
- name: Set required Core CI variables
  ansible.builtin.set_fact:
    terraform_cloud_token: "{{ lookup('env', 'TFC_CI_TOKEN') }}"
    terraform_cloud_organization: "{{ lookup('env', 'TFC_CI_ORGANIZATION') | default('ANSIBLE-ENGINEERING-CI', true) }}"
    destination_path: "~/.ansible/collections/ansible_collections/hashicorp/terraform/tests/integration/integration_config.yml"
  no_log: true

- name: Render integration_config.yml
  ansible.builtin.copy:
    dest: "{{ destination_path }}"
    content: "{{ lookup('template', 'integration_config.yml.j2') }}"
    mode: "0644"
  no_log: true

- name: Stat integration_config.yml file
  ansible.builtin.stat:
    path: "{{ destination_path }}"
  register: result

- name: Assert that integration_config.yml file exists
  ansible.builtin.assert:
    that: result.stat.exists
