---
- name: Set required Core CI variables
  ansible.builtin.set_fact:
    terraform_cloud_token: "{{ lookup('env', 'HCP_CI_TOKEN') }}"
    terraform_cloud_organization: "{{ lookup('env', 'HCP_CI_ORGANIZATION') }}"
    destination_path: "~/.ansible/collections/ansible_collections/hashicorp/terraform/tests/integration/integration_config.yml"
  no_log: true

- name: Set pre-provisioned stack fixture variables
  ansible.builtin.set_fact:
    stc_id: "{{ lookup('env', 'HCP_CI_STACK_CONFIGURATION_ID') }}"
    sdg_id: "{{ lookup('env', 'HCP_CI_STACK_DEPLOYMENT_GROUP_ID') }}"
    sdg_name: "{{ lookup('env', 'HCP_CI_STACK_DEPLOYMENT_GROUP_NAME') }}"
    stack_deployment_run_id: "{{ lookup('env', 'HCP_CI_STACK_DEPLOYMENT_RUN_ID') }}"
    stack_deployment_step_id: "{{ lookup('env', 'HCP_CI_STACK_DEPLOYMENT_STEP_ID') }}"
    stack_diagnostic_id: "{{ lookup('env', 'HCP_CI_STACK_DIAGNOSTIC_ID') }}"
    stack_state_id: "{{ lookup('env', 'HCP_CI_STACK_STATE_ID') }}"
  no_log: true

- name: Render integration_config.yml
  ansible.builtin.copy:
    dest: "{{ destination_path }}"
    content: "{{ lookup('template', 'integration_config.yml.j2') }}"
    mode: "0644"
  no_log: true

- name: Stat integration_config.yml file
  ansible.builtin.stat:
    path: "{{ destination_path }}"
  register: result

- name: Assert that integration_config.yml file exists
  ansible.builtin.assert:
    that: result.stat.exists
