---
name: Integration

on: # yamllint disable-line rule:truthy
  push:
    branches: [stable-1]
  pull_request:
    branches: [stable-1]
  workflow_dispatch:

jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible-version:
          - stable-2.19
          - devel
        python-version:
          - "3.13"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{github.event.pull_request.head.ref}}"
          repository: "${{ github.event.pull_request.head.repo.full_name }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ansible-core (${{ matrix.ansible-version }})
        run: python3 -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Install collection test dependencies
        run: >-
          python3 -m pip install -r test-requirements.txt

      - name: Build and install the collection
        run: >-
          ansible-galaxy collection install . --force

      - name: Generate integration_config.yml
        run: >-
          ansible-playbook tools/ci/playbooks/render_integration_config.yml
        env:
          ANSIBLE_CORE_CI_KEY: "${{ secrets.ANSIBLE_CORE_CI_KEY }}"
          TFC_CI_TOKEN: "${{ secrets.TFC_CI_TOKEN }}"

      - name: List all integration test targets
        run: >-
          cd ~/.ansible/collections/ansible_collections/hashicorp/terraform && \
            ansible-test integration --list-targets

      - name: Run integration tests (${{ matrix.ansible-version }})
        run: >-
          cd ~/.ansible/collections/ansible_collections/hashicorp/terraform && \
            ansible-test integration --python ${{ matrix.python-version }} --continue-on-error
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
