---
name: Integration

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, stable-1, stable-2]
  pull_request:
    branches: [main, stable-1, stable-2]
  workflow_dispatch:

jobs:
  run-integration-tests:
    name: Run Tests (ansible-${{ matrix.ansible-version }}, py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ansible-version: stable-2.16
            python-version: "3.12"
          - ansible-version: stable-2.19
            python-version: "3.13"
          - ansible-version: devel
            python-version: "3.13"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          ref: "${{github.event.pull_request.head.ref}}"
          repository: "${{ github.event.pull_request.head.repo.full_name }}"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install ansible-core (${{ matrix.ansible-version }})
        run: python3 -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Install collection test dependencies
        run: >-
          python3 -m pip install -r test-requirements.txt

      - name: Build and install the collection
        run: >-
          ansible-galaxy collection install . --force

      - name: Install collection dependencies
        run: >-
          ansible-galaxy collection install --pre -r tests/integration/requirements.yml

      - name: Generate integration_config.yml
        run: >-
          ansible-playbook tools/ci/playbooks/render_integration_config.yml
        env:
          HCP_CI_TOKEN: "${{ secrets.HCP_CI_TOKEN }}"
          HCP_CI_ORGANIZATION: "${{ secrets.HCP_CI_ORGANIZATION }}"

      - name: List all integration test targets
        run: >-
          cd ~/.ansible/collections/ansible_collections/hashicorp/terraform && \
            ansible-test integration --list-targets

      - name: Run integration tests (${{ matrix.ansible-version }})
        run: >-
          cd ~/.ansible/collections/ansible_collections/hashicorp/terraform && \
            ansible-test integration --python ${{ matrix.python-version }} --continue-on-error -vvvv
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
